// Single source of truth for the Amana Request record.
// Every other module in /intake (and later the website form, the WhatsApp
// bot, and the Hiyame integration) imports the field list and the empty-
// record factory from here, so the website form and the bot can never
// drift into writing different fields for the same thing.
//
// Plain JS + JSDoc, not TypeScript: this repo has no build step (see
// README.md), and adding one just for this module isn't worth it. The
// typedef below gives the same editor autocomplete/type-checking in VS
// Code without a compile step.

/**
 * @typedef {Object} AmanaRequest
 * @property {string} requestId            - e.g. "AMN-REQ-000123", generated by utils.generateRequestReference()
 * @property {string} createdAt            - ISO 8601 timestamp, set once on creation
 * @property {string} sourceChannel        - one of constants.SOURCE_CHANNELS
 * @property {string} sessionId            - WhatsApp bot session ID, or '' for non-bot sources
 * @property {string} status               - one of constants.ALL_STATUSES
 * @property {string} clientFullName
 * @property {string} clientPhone          - normalized E.164, see utils.normalizeNigerianPhone()
 * @property {string} clientEmail
 * @property {string} clientType           - one of constants.CLIENT_TYPES
 * @property {string} preferredContactChannel - one of constants.CONTACT_CHANNELS
 * @property {boolean} consent
 * @property {string} consentTimestamp     - ISO 8601, set when consent is true
 * @property {string} staffCategory        - one of constants.STAFF_CATEGORIES
 * @property {string} jobTitle
 * @property {number} numberRequired
 * @property {string} employmentType       - one of constants.EMPLOYMENT_TYPES
 * @property {string} liveArrangement      - one of constants.LIVE_ARRANGEMENTS
 * @property {string} state
 * @property {string} lga
 * @property {string} area
 * @property {string} responsibilities
 * @property {string} requiredSkills
 * @property {string} qualifications
 * @property {string} experience
 * @property {string} languages
 * @property {string} startDate            - ISO 8601 date, or '' if not given
 * @property {string} urgency              - one of constants.URGENCY_LEVELS
 * @property {string} workingDays
 * @property {string} workingHours
 * @property {boolean} accommodation
 * @property {boolean} meals
 * @property {number|null} salaryMin
 * @property {number|null} salaryMax
 * @property {string} currency             - default 'NGN'
 * @property {string} assignedRecruiter
 * @property {string} lastUpdatedAt         - ISO 8601, bumped on every write
 * @property {string} nextAction
 * @property {string} notes
 * @property {string} closureReason
 */

/** Fields in column order, for building Sheet headers / CSV exports from one place. */
const FIELD_ORDER = [
  'requestId', 'createdAt', 'sourceChannel', 'sessionId', 'status',
  'clientFullName', 'clientPhone', 'clientEmail', 'clientType', 'preferredContactChannel',
  'consent', 'consentTimestamp',
  'staffCategory', 'jobTitle', 'numberRequired', 'employmentType', 'liveArrangement',
  'state', 'lga', 'area',
  'responsibilities', 'requiredSkills', 'qualifications', 'experience', 'languages',
  'startDate', 'urgency', 'workingDays', 'workingHours', 'accommodation', 'meals',
  'salaryMin', 'salaryMax', 'currency',
  'assignedRecruiter', 'lastUpdatedAt', 'nextAction', 'notes', 'closureReason',
];

/**
 * Returns a fresh, empty AmanaRequest with every field present (never
 * `undefined`), so a partial object from a form or a bot step can be
 * spread over this without silently missing a column when it's written
 * to the Sheet.
 * @returns {AmanaRequest}
 */
function createEmptyRequest() {
  return {
    requestId: '',
    createdAt: '',
    sourceChannel: '',
    sessionId: '',
    status: '',
    clientFullName: '',
    clientPhone: '',
    clientEmail: '',
    clientType: '',
    preferredContactChannel: '',
    consent: false,
    consentTimestamp: '',
    staffCategory: '',
    jobTitle: '',
    numberRequired: 1,
    employmentType: '',
    liveArrangement: '',
    state: '',
    lga: '',
    area: '',
    responsibilities: '',
    requiredSkills: '',
    qualifications: '',
    experience: '',
    languages: '',
    startDate: '',
    urgency: '',
    workingDays: '',
    workingHours: '',
    accommodation: false,
    meals: false,
    salaryMin: null,
    salaryMax: null,
    currency: 'NGN',
    assignedRecruiter: '',
    lastUpdatedAt: '',
    nextAction: '',
    notes: '',
    closureReason: '',
  };
}

/**
 * Fields that must be non-empty before a request can move out of the
 * Intake phase (status New/Confirmed). Used by both the website form's
 * server-side validation and the bot's step-14 review/confirm gate, so
 * the two channels enforce the same minimum bar.
 */
const REQUIRED_FOR_CONFIRMATION = [
  'clientFullName', 'clientPhone', 'clientType', 'consent',
  'staffCategory', 'numberRequired', 'state',
];

/**
 * Checks an AmanaRequest-shaped object against REQUIRED_FOR_CONFIRMATION.
 * @param {Partial<AmanaRequest>} record
 * @returns {{ valid: boolean, missing: string[] }}
 */
function validateForConfirmation(record) {
  const missing = REQUIRED_FOR_CONFIRMATION.filter((field) => {
    const v = record[field];
    if (typeof v === 'boolean') return v !== true;
    return v === undefined || v === null || String(v).trim() === '';
  });
  return { valid: missing.length === 0, missing };
}

module.exports = {
  FIELD_ORDER,
  createEmptyRequest,
  REQUIRED_FOR_CONFIRMATION,
  validateForConfirmation,
};
